name: Otus homework tests

on:
  push:
    branches:
      - master
      - hw*

env:
  GO111MODULE: 'on'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Unit tests
        run: go test -v -timeout=10m -p 1 ./...
